export const ecommerceService = {
  eyebrow: "E-commerce design & development",
  title: "Your products deserve",
  accent: "a store of their own.",
  intro: "A considered shopping experience, built around your brand and the way you work. From storefront design to payments, delivery and everyday management, I help bring your online store together.",
  benefits: ["Custom storefront design", "Connected to your business", "Support beyond launch"],
  solutions: {
    eyebrow: "Room for your next chapter",
    title: "A store shaped around you.",
    intro: "The right setup depends on your catalogue, workflows and plans. We agree on the platform and features around your project’s size and budget.",
    items: [
      { title: "Your first online store", text: "Bring your products online with clear collections, considered product pages and an easy path to checkout." },
      { title: "A fresh start for your existing store", text: "Redesign your storefront and plan the transfer of agreed products and content, with redirects and launch checks included in the migration scope." },
      { title: "Connected commerce", text: "Connect your store with stock, delivery, accounting or other business tools through available APIs. Each integration is reviewed for compatibility and scope." },
      { title: "Help with everyday management", text: "Get support with product uploads, collection updates, content changes and agreed store administration, at launch or on an ongoing basis." },
    ],
  },
  included: [
    { title: "Storefront design & development", text: "A responsive Next.js storefront with the agreed collection, product and shopping journeys, designed around your brand." },
    { title: "Commerce & content management", text: "Shopify in a headless setup, another headless platform or a custom CMS and commerce backend, selected around your requirements." },
    { title: "Payments & delivery setup", text: "Help configuring supported payment providers, shipping methods and delivery integrations for your market and platform." },
    { title: "Products, ready to browse", text: "Help setting up products, variants, categories and images. We agree on the number of products and any import or data cleanup before starting." },
    { title: "API integrations", text: "Connect agreed business systems and plan how information moves between them, including the checks needed when something fails." },
    { title: "Testing, launch & handover", text: "Review mobile shopping, test checkout and order flows, set up basic search foundations and walk through your store’s daily management." },
  ],
  audiences: [
    { title: "Launching a new brand", text: "Start with a focused store and a clear way to manage your products and orders." },
    { title: "Ready for a more tailored experience", text: "Shape your customer journey around your products, with a custom storefront and agreed integrations." },
    { title: "Looking for a long-term helping hand", text: "Arrange product uploads, content updates and store administration as an ongoing service, with responsibilities agreed together." },
  ],
  steps: [
    { title: "Plan the store", text: "We map your catalogue, market and workflows, then agree on the platform, integrations, scope and quote." },
    { title: "Design the experience", text: "We review the key shopping pages and mobile journey together before development begins." },
    { title: "Build & connect", text: "I build the storefront, configure the agreed management tools and connect payments, shipping and other services." },
    { title: "Test, launch & support", text: "We check the buying journey and order handling, prepare your products and agree on handover or ongoing management." },
  ],
  headless: {
    eyebrow: "Headless, without the jargon",
    title: "Your storefront. Your management tools. Connected.",
    intro: "Headless means the shop your customers see is built separately from the system you use to manage products and orders. The two exchange information through an API — a connection between systems.",
    comparison: "In a traditional theme-based store, the storefront and management platform are more tightly linked. A headless setup lets me design your storefront separately while keeping suitable tools behind the scenes.",
    reasons: [
      { title: "More freedom for your brand", text: "I can shape layouts and shopping journeys around your products, rather than starting with the limits of a particular store theme." },
      { title: "Tools that fit your workflow", text: "We can keep a suitable commerce platform and connect the additional services your business needs." },
      { title: "Room to evolve", text: "The storefront and management tools can evolve separately, with changes planned around their connections." },
    ],
    approach: "This is why I build with a headless approach: it gives me control over the customer experience and flexibility in how the store connects to your business. It also needs more development and maintenance than a simple theme-based shop. It is not automatically faster or cheaper; we choose the scope carefully.",
    stack: "A custom Next.js storefront can connect to Shopify for commerce, another headless platform, or a tailored backend with a custom CMS. A CMS manages content; the commerce system handles products, orders and checkout. The project determines which combination makes sense.",
  },
  faqs: [
    { question: "Can I still manage products and orders myself?", answer: "Yes. The project includes an agreed management setup and a handover. We define which content and store settings you can edit yourself; changes to the custom storefront layout may require development." },
    { question: "Which platform will my store use?", answer: "The storefront is built with Next.js. Depending on the project, it can connect to Shopify, another headless commerce platform or a custom backend and CMS. We choose based on your catalogue, workflows, integrations and budget." },
    { question: "Can you set up payments and delivery?", answer: "Yes. I can help configure suitable providers and connect supported delivery services. Availability depends on your market and platform. You provide the required business accounts and approvals; provider fees are separate." },
    { question: "Can you upload my products or move an existing catalogue?", answer: "Yes. Product setup and migration can be part of the project. We agree on quantities, variants, images, source data and cleanup work first. You provide accurate product information and pricing." },
    { question: "Can you connect the store to other systems?", answer: "Yes, where the systems offer suitable API access. We review requirements and limitations before confirming an integration, including data synchronisation, access costs and maintenance." },
    { question: "Can you manage the store after launch?", answer: "Yes. Ongoing product uploads, collection changes, content updates and agreed administration can be arranged. Technical maintenance and development can also be scoped separately. We agree on tasks, access and response expectations before starting." },
    { question: "How much will it cost, and how long will it take?", answer: "The quote and schedule depend on the design, catalogue, backend and integrations. Hosting, platform subscriptions and third-party fees are outlined separately. We agree on the scope, price and timeline before development." },
  ],
};
