export const seoService = {
  eyebrow: "SEO basics",
  title: "A clearer website.",
  accent: "A stronger starting point.",
  intro: "Help people and search engines understand what your business offers. I review your existing website, tidy up the essentials and leave you with a clear picture of what comes next.",
  benefits: ["Practical improvements", "Clear priorities", "No ranking promises"],
  solutions: {
    eyebrow: "Start with the foundations",
    title: "Make the essentials make sense.",
    intro: "SEO basics is a focused review and implementation service for existing websites. We agree on the pages and changes first, based on your business and the access your platform allows.",
    items: [
      { title: "A website that needs a tidy-up", text: "Bring page titles, descriptions, headings and internal links into line with what your business actually offers." },
      { title: "A recent launch or redesign", text: "Review the agreed pages for missing search essentials, broken links and unintentional barriers to discovery." },
      { title: "Unclear search visibility", text: "Use available Search Console information to investigate indexing issues and identify practical next steps." },
      { title: "A plan you can follow", text: "Finish with a record of completed changes and a prioritised list of anything that needs further content or development work." },
    ],
  },
  included: [
    { title: "A focused website review", text: "Review the agreed pages and identify missing basics, unclear structure and issues worth addressing first." },
    { title: "Titles & descriptions", text: "Write or refine descriptive page titles and meta descriptions that reflect each page’s content and purpose." },
    { title: "Headings, links & images", text: "Improve heading structure, relevant internal links and useful alternative text for meaningful images." },
    { title: "Discovery & indexing checks", text: "Check the sitemap, relevant indexing directives and obvious broken links or canonical issues. Apply agreed fixes where access allows." },
    { title: "Search Console setup", text: "Help verify your property, submit the sitemap where appropriate and review available indexing information with you." },
    { title: "A practical handover", text: "Receive a summary of completed work, outstanding issues and sensible next steps for keeping your website organised." },
  ],
  audiences: [
    { title: "You already have a website", text: "Your business is online, but the search essentials have never had a proper review." },
    { title: "Your business has changed", text: "Your services or audience have evolved and your pages need to tell a clearer, more consistent story." },
    { title: "You want a manageable first step", text: "Start with a defined piece of work and understand what needs attention before committing to a broader SEO programme." },
  ],
  steps: [
    { title: "Agree on the focus", text: "We discuss your business, choose the pages to review and confirm platform access, scope and quote." },
    { title: "Review & prioritise", text: "I inspect the agreed pages and available search data, then explain the findings and proposed changes." },
    { title: "Put the basics in place", text: "I implement the approved changes. Work that needs a larger rebuild or extra access is discussed separately." },
    { title: "Check & hand over", text: "I check the updates and share what changed, what remains and how to use the available Search Console information." },
  ],
  scope: {
    eyebrow: "Clear expectations",
    title: "A foundation you can build on.",
    text: "This service covers an agreed set of on-page and technical basics. Ongoing content production, link building, paid ads, extensive keyword research and large technical rebuilds are outside the standard scope.",
    note: "Search engines decide what to index and how to rank it. Changes may take time to be reflected, and no position, traffic increase or indexing outcome is guaranteed.",
    includedTitle: "Building a new website with ByLili?",
    includedText: "The basic search setup is already part of your website or e-commerce project. This separate service is for an existing website or additional work beyond the agreed build scope.",
  },
  faqs: [
    { question: "Will my website reach the first page of Google?", answer: "No one can promise a particular position. This service improves the agreed foundations and addresses identified issues. Search visibility also depends on your content, competition and other factors outside this work." },
    { question: "Is this included with a new ByLili website?", answer: "Yes, the basic search setup is included in a new website or e-commerce build. SEO Basics is a separate service for existing websites or additional work outside that project’s agreed scope." },
    { question: "Can you work on a website someone else built?", answer: "Yes, subject to a review of the platform and available access. I confirm which changes are possible before quoting. Larger code changes or platform limitations are discussed separately." },
    { question: "Does this include blog posts or ongoing SEO?", answer: "The standard service is a focused review and implementation project. Regular content production, extensive keyword research, link building and ongoing SEO campaigns are not included. Any additional work is agreed separately." },
    { question: "What access will you need?", answer: "Depending on the scope, I may need website or CMS access and permission to your Search Console property. Domain access may be needed for verification. We agree on the permissions required, with accounts remaining under your ownership." },
    { question: "How soon will I see changes in search?", answer: "Website changes can be checked after implementation, but search engines need time to revisit and process them. There is no fixed timetable or guaranteed result. Search Console helps you monitor available data over time." },
    { question: "Will Google show the exact title and description we write?", answer: "Not always. Search engines can use other page content to generate the title or snippet. Clear, relevant titles and descriptions are useful inputs, not a fixed preview of every search result." },
    { question: "How is the work priced?", answer: "The quote depends on the number of pages, platform, access and fixes required. We agree on the scope and price before work begins; additional development is quoted separately." },
  ],
};
